In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [91]:
#creating a 2-D array
b = np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [86]:
c = np.array([0,1])
c

array([0, 1])

In [ ]:
x = 

In [89]:
#np array of shape(2,3,4) 4-col, 3-rows, 
c = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
c.shape

(2, 3, 4)

In [47]:
#slicing
arr = np.array([1,2,3,4,5])
arr[1:3] # it starts from 1(index) and goes till 3(index) , with 3 not included

array([2, 3])

In [48]:
arr = np.array([1,2,3,4,5])
arr[1:] #starts from the first index and goes till the end

array([2, 3, 4, 5])

In [49]:
arr = np.array([1,2,3,4,5])
arr[:4] #starts from zero index and goes till 3 (4 not included)

array([1, 2, 3, 4])

In [53]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[1:5:2] # starts from the first index and goes till the fourth with an increment of 2

array([2, 4])

In [54]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4]

array([7, 8, 9])

In [58]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 2]

array([3, 8])

In [59]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 0:2]

array([[1, 2],
       [6, 7]])

In [60]:
#data types 
a = np.array([1,2,3,4,5])
a.dtype
#integer

dtype('int32')

In [63]:
b = np.array(["sai", "ram"])
b.dtype
#unicode

dtype('<U3')

In [68]:
b = np.array([1,2,3,4], dtype = 'S')
b.dtype
#String

dtype('S1')

In [83]:
arr = np.array([1.2, 2.6])
newarr = arr.astype('i') #typecasting
print(arr.dtype)
print(newarr)
print(newarr.dtype)

float64
[1 2]
int32


In [87]:
arr = np.array([1,2.3,0])
newarr = arr.astype(bool)

print(arr)
print(newarr)

[1.  2.3 0. ]
[ True  True False]


In [102]:
c = np.array([7,4,-4], dtype = complex)
c

array([ 7.+0.j,  4.+0.j, -4.+0.j])

In [143]:
x = np.zeros((4,2,3)) #will enter o as the value and default type float
x

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [119]:
z = np.ones_like((x), dtype = int) # intial value as 1 and type int
z

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [123]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [133]:
a = np.arange(0,7,2)
a

array([0, 2, 4, 6])

In [142]:
a = np.linspace(0,2,5) # starting , ending, the number of values/parts
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [151]:
def f(i,j):
    return 1*i*J

x = np.fromfunction(f,(4,3)) # to initialize an array from a function
x # 4,3 is the dimention of the array

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [164]:
np.fromfunction(lambda i,j: 3*i*j, (4,3)) #short hand form of from function(4,3)

array([[ 0.,  0.,  0.],
       [ 0.,  3.,  6.],
       [ 0.,  6., 12.],
       [ 0.,  9., 18.]])

In [161]:
#universal functions
x = np.linspace(1,5,5)
y = x**2
print(y)
z = np.sqrt(y)
print(z)

[ 1.  4.  9. 16. 25.]
[1. 2. 3. 4. 5.]


In [179]:
#matrix multiply
a = np.array(((1,2),(3,4)))
print(a,"\n")
print(a.T)  #transpose of the matrix
b = a
print(b,"\n")
print(a*b, "\n") #element wise multiplication
print(np.matmul(a,b)) #matrix multiplication
print(np.dot(a,b))

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]
[[1 2]
 [3 4]] 

[[ 1  4]
 [ 9 16]] 

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [185]:
# Magic square

N = 3
msqr = np.zeros((N,N), dtype = int)

n = 1
i, j = 0, N//2

while n <= N**2:
    msqr[i,j] = n
    n += 1
    ni, nj = (i-1)%N, (j+1)%N
    if msqr[ni, nj]:
        i += 1
    else:
        i, j = ni, nj
msqr

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [192]:
#flaten -> multidimentional array into single axis
       #-> two methods fltten and ravel

z = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
x = z.flatten()
print(z)
print(x)
y = z.ravel()
print(y)


        

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
