In [2]:
import numpy as np

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [91]:
#creating a 2-D array
b = np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [86]:
c = np.array([0,1])
c

array([0, 1])

In [ ]:
x = 

In [89]:
#np array of shape(2,3,4) 4-col, 3-rows, 
c = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
c.shape

(2, 3, 4)

In [47]:
#slicing
arr = np.array([1,2,3,4,5])
arr[1:3] # it starts from 1(index) and goes till 3(index) , with 3 not included

array([2, 3])

In [48]:
arr = np.array([1,2,3,4,5])
arr[1:] #starts from the first index and goes till the end

array([2, 3, 4, 5])

In [49]:
arr = np.array([1,2,3,4,5])
arr[:4] #starts from zero index and goes till 3 (4 not included)

array([1, 2, 3, 4])

In [53]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[1:5:2] # starts from the first index and goes till the fourth with an increment of 2

array([2, 4])

In [54]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4]

array([7, 8, 9])

In [58]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 2]

array([3, 8])

In [59]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 0:2]

array([[1, 2],
       [6, 7]])

In [60]:
#data types 
a = np.array([1,2,3,4,5])
a.dtype
#integer

dtype('int32')

In [63]:
b = np.array(["sai", "ram"])
b.dtype
#unicode

dtype('<U3')

In [68]:
b = np.array([1,2,3,4], dtype = 'S')
b.dtype
#String

dtype('S1')

In [83]:
arr = np.array([1.2, 2.6])
newarr = arr.astype('i') #typecasting
print(arr.dtype)
print(newarr)
print(newarr.dtype)

float64
[1 2]
int32


In [87]:
arr = np.array([1,2.3,0])
newarr = arr.astype(bool)

print(arr)
print(newarr)

[1.  2.3 0. ]
[ True  True False]


In [102]:
c = np.array([7,4,-4], dtype = complex)
c

array([ 7.+0.j,  4.+0.j, -4.+0.j])

In [143]:
x = np.zeros((4,2,3)) #will enter o as the value and default type float
x

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [119]:
z = np.ones_like((x), dtype = int) # intial value as 1 and type int
z

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [123]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [133]:
a = np.arange(0,7,2)
a

array([0, 2, 4, 6])

In [142]:
a = np.linspace(0,2,5) # starting , ending, the number of values/parts
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [151]:
def f(i,j):
    return 1*i*J

x = np.fromfunction(f,(4,3)) # to initialize an array from a function
x # 4,3 is the dimention of the array

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [164]:
np.fromfunction(lambda i,j: 3*i*j, (4,3)) #short hand form of from function(4,3)

array([[ 0.,  0.,  0.],
       [ 0.,  3.,  6.],
       [ 0.,  6., 12.],
       [ 0.,  9., 18.]])

In [161]:
#universal functions
x = np.linspace(1,5,5)
y = x**2
print(y)
z = np.sqrt(y)
print(z)

[ 1.  4.  9. 16. 25.]
[1. 2. 3. 4. 5.]


In [179]:
#matrix multiply
a = np.array(((1,2),(3,4)))
print(a,"\n")
print(a.T)  #transpose of the matrix
b = a
print(b,"\n")
print(a*b, "\n") #element wise multiplication
print(np.matmul(a,b)) #matrix multiplication
print(np.dot(a,b))

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]
[[1 2]
 [3 4]] 

[[ 1  4]
 [ 9 16]] 

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [185]:
# Magic square

N = 3
msqr = np.zeros((N,N), dtype = int)

n = 1
i, j = 0, N//2

while n <= N**2:
    msqr[i,j] = n
    n += 1
    ni, nj = (i-1)%N, (j+1)%N
    if msqr[ni, nj]:
        i += 1
    else:
        i, j = ni, nj
msqr

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [192]:
#flaten -> multidimentional array into single axis
       #-> two methods flatten and ravel

z = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
x = z.flatten()
print(z)
print(x)
y = z.ravel()
print(y)
# flatten returns independent copy of the element, slower than ravel.

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [8]:
a =np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
b = a.flatten()
b[3]


4

In [11]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
c = a.ravel()
c


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a = np.array([1,2,3,4,5,7,6,8,9])
a.resize(2,2,2)
print(a)

[[[1 2]
  [3 4]]

 [[5 7]
  [6 8]]]


In [36]:
#transposing
a = np.linspace(1,8,8)
print(a)
b = a.reshape(2,2,2)
print(b)
c = b.transpose()
print(c)
print(c.shape)


[1. 2. 3. 4. 5. 6. 7. 8.]
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
[[[1. 5.]
  [3. 7.]]

 [[2. 6.]
  [4. 8.]]]
(2, 2, 2)


In [39]:
# merge and split

a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.dstack((a,b)) #stacks arrays depthwise 
c

array([[[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]]])

In [42]:
c = np.vstack((a,b)) # stacks arrays vertically/ in sequential rows
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
c =np.hstack((a,b)) # stacks arrays horizontally/ in sequential columns
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
d = np.arange(16).reshape(4,4)
print(d)
e = np.hsplit(d,2) #???
print(e)
f = np.vsplit(d,2) 
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [67]:
a = np.linspace(1,10,10)
print(a)
print(a[1:5:2])# (start, end(not iclusive), jump to next)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2. 4.]


In [83]:
a = np.linspace(1,12,12).reshape(4,3)
print(a)
print(a[3:4]) # third row strat is not included
print(a[2:]) # second and third row

print(a[:,1]) # 2nd col
print(a[:,0]) # 1st col

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
[[10. 11. 12.]]
[[ 7.  8.  9.]
 [10. 11. 12.]]
[ 2.  5.  8. 11.]
[ 1.  4.  7. 10.]


In [84]:
a = np.linspace(1,10,10)
print(a)
ia = [1,5,7] # index
print(a[ia]) #printing index 1,5,7

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2. 6. 8.]


In [86]:
ia = np.array(((1,3),(5,7),(2,3)))# (1,3), (5,7), (2,3) as independent rows of a matrix
print(a[ia]) 

[[2. 4.]
 [6. 8.]
 [3. 4.]]


In [88]:
# sorting array

a = np.array([4,2,7,1,9,23,5])
print(a)
a.sort() #sort the array in ascending order
print(a)


[ 4  2  7  1  9 23  5]
[ 1  2  4  5  7  9 23]


In [102]:
a = np.array([[1,25,12],[1,5,2],[3,9,2]])
print(a)
a.sort() # sorting all the rows
print(a)

[[ 1 25 12]
 [ 1  5  2]
 [ 3  9  2]]
[[ 1 12 25]
 [ 1  2  5]
 [ 2  3  9]]


In [104]:
a.sort(axis=0) # sorting every row
print(a)

[[ 1  2  5]
 [ 1  3  9]
 [ 2 12 25]]


In [109]:
a = np.array([3,6,2,5,67,1,2,6,])
np.argsort(a) #prints the index instead of the values

array([5, 2, 6, 0, 3, 1, 7, 4], dtype=int64)

In [116]:
# statistics
a = np.array([3,6,2,5,67,1,2,6,])
b = np.array([4,2,7,1,9,23,5,34])
print(np.min(a)) #prints the min element
print(np.max(a)) #prints the max element
print(np.argmax(a)) #print the index of the max value i.e 67
c = np.fmax(a,b) #returns the max element of the two arrays
print(c)         #element wise comparison

1
67
4
[ 4  6  7  5 67 23  5 34]


In [117]:
#percentiles
a = np.array([[1,25,4,8,12],[1,5,3,9,2]])
np.percentile(a,75) # returns the 75th percentile of a

8.75

In [125]:
#sample statistics
x = np.array([[1,25,4,8,12]])
print(np.mean(x)) #mean of the array
print(np.median(x))
print(np.std(x)) #standard deviation
print(np.var(x)) # variance

10.0
8.0
8.366600265340756
70.0
